project_id = "uzcmjulbpmeythxfusrm"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev/preview"]
jwt_expiry = 3600

[auth.email]

[functions.admin-create-user]
verify_jwt = false

[functions.agency-create-advertiser]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.fix-user-roles]
verify_jwt = false
