#!/usr/bin/env python3
import argparse
import os
import sys
from pathlib import Path

def main():
    parser = argparse.ArgumentParser(description='Run agent')
    parser.add_argument('--agent', required=True, help='Agent to run')
    args = parser.parse_args()
    
    if args.agent == 'product_manager':
        run_product_manager()
    else:
        print(f"Unknown agent: {args.agent}")
        sys.exit(1)

def run_product_manager():
    """Run the product manager agent"""
    print("Running Product Manager Agent...")
    
    # Create a minimal PRD
    prd_content = """# Product Requirements Document

## Overview
This is a minimal PRD generated by the Product Manager Agent.

## Features
- Feature 1
- Feature 2
- Feature 3

## Technical Requirements
- Requirement 1
- Requirement 2
- Requirement 3

## Success Metrics
- Metric 1
- Metric 2
- Metric 3
"""
    
    # Create a minimal backlog
    backlog_content = """id,title,description,status,priority
1,Implement feature 1,Implement the first feature,To Do,High
2,Implement feature 2,Implement the second feature,To Do,Medium
3,Implement feature 3,Implement the third feature,To Do,Low
"""
    
    # Write files
    outputs_dir = Path("agenthub/outputs")
    outputs_dir.mkdir(exist_ok=True)
    
    (outputs_dir / "prd.md").write_text(prd_content)
    (outputs_dir / "backlog.csv").write_text(backlog_content)
    
    print("Product Manager Agent completed successfully!")
    print(f"Generated files in {outputs_dir}")

if __name__ == "__main__":
    main()