name: Agent Pipeline (PM only)

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  LLM_MODEL: gpt-4o-mini

jobs:
  product_manager:
    name: Product Manager
    runs-on: ubuntu-latest
    environment: product-manager

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install "openai>=1.30.0"
          python - <<'PY'
          import os, importlib.metadata as im
          print("OPENAI_API_KEY set:", bool(os.environ.get("OPENAI_API_KEY")))
          print("openai version:", im.version("openai"))
          PY
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Preflight OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LLM_MODEL: ${{ env.LLM_MODEL }}
        run: |
          python - <<'PY'
          import os, sys
          from openai import OpenAI
          key = os.environ.get("OPENAI_API_KEY")
          mdl = os.environ.get("LLM_MODEL","gpt-4o-mini")
          if not key:
            print("❌ OPENAI_API_KEY missing (add it in Settings → Secrets → Actions).")
            sys.exit(2)
          try:
            client = OpenAI(api_key=key)
            client.chat.completions.create(
              model=mdl,
              messages=[{"role":"system","content":"ping"},{"role":"user","content":"pong"}],
              max_tokens=5
            )
            print("✅ Preflight OK on model:", mdl)
          except Exception as e:
            print("❌ Preflight failed:", e)
            sys.exit(2)
          PY

      - name: Run Product Manager Agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LLM_MODEL: ${{ env.LLM_MODEL }}
        run: python agenthub/run.py --agent product_manager

      - name: Upload PRD and Backlog
        uses: actions/upload-artifact@v4
        with:
          name: product-manager-artifacts
          path: |
            agenthub/outputs/prd.md
            agenthub/outputs/backlog.csv
