  product_manager:
    name: Product Manager
    runs-on: ubuntu-latest
    environment: product-manager
    env:
      LLM_MODEL: gpt-4o-mini   # change if you don't have access to this
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -V
          python -m pip install --upgrade pip
          pip install "openai>=1.30.0"
          python - <<'PY'
          import os, pkgutil
          print("OPENAI_API_KEY set:", bool(os.environ.get("OPENAI_API_KEY")))
          import importlib.metadata as im
          print("openai version:", im.version("openai"))
          PY
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Preflight OpenAI (clear error if misconfigured)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LLM_MODEL: ${{ env.LLM_MODEL }}
        run: |
          python - <<'PY'
          import os, sys
          from openai import OpenAI
          key = os.environ.get("OPENAI_API_KEY")
          if not key:
            print("❌ OPENAI_API_KEY is missing (Actions → Secrets)."); sys.exit(2)
          model = os.environ.get("LLM_MODEL","gpt-4o-mini")
          try:
            client = OpenAI(api_key=key)
            r = client.chat.completions.create(
              model=model,
              messages=[{"role":"system","content":"ping"},{"role":"user","content":"pong"}],
              max_tokens=5,
            )
            print("✅ Preflight completion OK on model:", model)
          except Exception as e:
            print("❌ Preflight failed:", e)
            sys.exit(2)
          PY

      - name: Run Product Manager Agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LLM_MODEL: ${{ env.LLM_MODEL }}
        run: python agenthub/run.py --agent product_manager

      - name: Upload PRD and Backlog
        uses: actions/upload-artifact@v4
        with:
          name: product-manager-artifacts
          path: |
            agenthub/outputs/prd.md
            agenthub/outputs/backlog.csv
