name: Auto Deploy & QA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  deploy:
    name: Deploy Backend (Render) & Frontend (Vercel)
    runs-on: ubuntu-latest
    env:
      RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
      VERCEL_DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}
    steps:
      - name: Trigger Render backend deploy
        if: ${{ env.RENDER_DEPLOY_HOOK != '' }}
        run: |
          curl -fsSL -X POST "$RENDER_DEPLOY_HOOK"
          echo "Render deploy hook triggered."

      - name: Trigger Vercel frontend deploy
        if: ${{ env.VERCEL_DEPLOY_HOOK != '' }}
        run: |
          curl -fsSL -X POST "$VERCEL_DEPLOY_HOOK"
          echo "Vercel deploy hook triggered."

  wait_for_backend:
    name: Wait for Backend Health
    needs: [deploy]
    runs-on: ubuntu-latest
    env:
      API_BASE_URL: ${{ vars.API_BASE_URL }}
    steps:
      - name: Poll health endpoint
        run: |
          echo "Checking Supabase backend at $API_BASE_URL ..."
          for i in {1..10}; do
            code=$(curl -sk -o /dev/null -w "%{http_code}" "$API_BASE_URL/rest/v1/")
            if [ "$code" = "200" ] || [ "$code" = "401" ]; then
              echo "Supabase backend is healthy."
              exit 0
            fi
            echo "Not ready yet ($i/10). Sleeping 5s..."
            sleep 5
          done
          echo "Backend did not respond in time."
          exit 1

  qa_agents:
    name: Run Agent Pipeline (includes QA)
    needs: [wait_for_backend]
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      EQUATIV_API_KEY: ${{ secrets.EQUATIV_API_KEY }}
      MINIMAX_API_KEY: ${{ secrets.MINIMAX_API_KEY }}
      MINIMAX_GROUP_ID: ${{ secrets.MINIMAX_GROUP_ID }}
      DEFAULT_AGENCY_MARGIN_PCT: ${{ secrets.DEFAULT_AGENCY_MARGIN_PCT }}
      DEFAULT_ADMIN_BUFFER_PCT: ${{ secrets.DEFAULT_ADMIN_BUFFER_PCT }}
      API_BASE_URL: ${{ vars.API_BASE_URL }}
      GH_TOKEN: ${{ github.token }}   # token for gh CLI
    steps:
      # GitHub-hosted runners already include gh; no install needed
      - name: Trigger existing Agent Pipeline workflow
        run: |
          # Change this if your workflow has a different display name
          wf_name="Agent Pipeline"
          echo "Triggering \"$wf_name\" on main ..."
          gh workflow run "$wf_name" --ref main
          echo "Waiting for the run to start..."
          sleep 10
          gh run watch --exit-status

      - name: Smoke test Pricing API
        run: |
          curl -fsSL "${API_BASE_URL}/api/campaigns/price?base=1000&agency_pct=15&admin_pct=5" || exit 1

      - name: Smoke test Creative (text)
        run: |
          curl -fsSL -X POST "${API_BASE_URL}/api/creatives/text" \
            -H "Content-Type: application/json" \
            -d '{"product":"Sneaker X","audience":"runners in Mumbai"}' || exit 1
